### ISSUE TITLE
tt_content record with uid 1 gets random pid values

### ISSUE THREAD

**Issue by pi-phi** [FluidTYPO3/fluidcontent#236] opened 2015-04-16 12:30 UTC
every now and then it occurs that the tt_content record with uid 1(!) is moved to another page (just found -2148?(missed to write down the value before change in DB)  instead of 516). 
the record has CType 'menu' and menu_type 8 but I think it's the uid which may be grabbed somewhere and the record is modified unintended.

on the page the record is inserted (516) no edits take place, especially the record itself is not edited.
so I have no clue what action triggers the 'moving'.

the usual suspects: 
gridelements(3.1.0) and 
fluid_content(4.0.0) on 
TYPO3 CMS 6.2.11

**Comment by NamelessCoder** [comment] 2015-04-21 16:57
Hmm... I am quite confident this is not caused by fluidcontent or flux. If either extension ever detects a negative colPos it will assume a "relative to this element" instruction and resolve the colPos+pid+tx_flux_parent+tx_flux_column values accordingly. So if Flux was doing this because of something triggered in DataHandler, you'd expect to see the record actually ending up with the same PID value as `tt_content:2148` in your case. The only place a UID/PID of `1` is forced in Flux etc. is in the unit tests and those are specifically designed to *completely* avoid any DB calls and only run separately from TYPO3 - so I assume these aren't the cause either.

To me, this sounds like perhaps some extension either incorrectly manipulates a value passed by reference in DataHandler or somehow incorrectly calls DataHandler methods (the `1` could indicate the intention was to pass a boolean; it actually being hardcoded as intended UID sounds implausible).

If any extension (and this might include gridelements) comes *after* Flux in the load order and does *not* do similar checking before storing a record, this could very well be the cause. IIRC, gridelements still inserts itself with "bottom" priority which means it would definitely come after Flux.

PS: If you ever spot a negative PID value that's extremely low (-1,000,000,000 and below) then Flux is your main suspect. This would indicate an issue in Flux's internal resolving of said relationship values!

**Closed by NamelessCoder** 2015-04-21 16:57 UTC
