### ISSUE TITLE
PHP Fatal error with version 4.3.1

### ISSUE THREAD

**Issue by munix9** [FluidTYPO3/fluidcontent#264] opened 2015-08-09 14:23 UTC
with version 4.3.1 from ter this happens when trying to clear caches in backend:

```
PHP Fatal error:  Call to a member function getSessionData() on null in /srv/www/vhosts/xyz/typo3_src-6.2.14/typo3/sysext/core/Classes/Messaging/FlashMessageQueue.php on line 134
PHP Stack trace:
PHP   1. {main}() /srv/www/vhosts/xyz/typo3_src-6.2.14/typo3/tce_db.php:0
PHP   2. require() /srv/www/vhosts/xyz/typo3_src-6.2.14/typo3/tce_db.php:23
PHP   3. TYPO3\CMS\Core\Core\Bootstrap->loadExtensionTables() /srv/www/vhosts/xyz/typo3_src-6.2.14/typo3/init.php:56
PHP   4. TYPO3\CMS\Core\Core\Bootstrap->runExtTablesPostProcessingHooks() /srv/www/vhosts/xyz/typo3_src-6.2.14/typo3/sysext/core/Classes/Core/Bootstrap.php:946
PHP   5. FluidTYPO3\Fluidcontent\Backend\TableConfigurationPostProcessor->processData() /srv/www/vhosts/xyz/typo3_src-6.2.14/typo3/sysext/core/Classes/Core/Bootstrap.php:992
PHP   6. FluidTYPO3\Fluidcontent\Service\ConfigurationService->getPageTsConfig() /srv/www/vhosts/xyz/htdocs/typo3conf/ext/fluidcontent/Classes/Backend/TableConfigurationPostProcessor.php:30
PHP   7. FluidTYPO3\Fluidcontent\Service\ConfigurationService->renderPageTypoScriptForPageUid() /srv/www/vhosts/xyz/htdocs/typo3conf/ext/fluidcontent/Classes/Service/ConfigurationService.php:134
PHP   8. FluidTYPO3\Fluidcontent\Service\ConfigurationService->buildAllWizardTabGroups() /srv/www/vhosts/xyz/htdocs/typo3conf/ext/fluidcontent/Classes/Service/ConfigurationService.php:161
PHP   9. FluidTYPO3\Fluidcontent\Service\ConfigurationService->getContentElementFormInstances() /srv/www/vhosts/xyz/htdocs/typo3conf/ext/fluidcontent/Classes/Service/ConfigurationService.php:225
PHP  10. FluidTYPO3\Fluidcontent\Service\ConfigurationService->sendDisabledContentWarning() /srv/www/vhosts/xyz/htdocs/typo3conf/ext/fluidcontent/Classes/Service/ConfigurationService.php:273
PHP  11. FluidTYPO3\Flux\Service\FluxService->message() /srv/www/vhosts/xyz/htdocs/typo3conf/ext/fluidcontent/Classes/Service/ConfigurationService.php:384
PHP  12. TYPO3\CMS\Core\Messaging\FlashMessageQueue->addMessage() /srv/www/vhosts/xyz/htdocs/typo3conf/ext/flux/Classes/Service/FluxService.php:458
PHP  13. TYPO3\CMS\Core\Messaging\FlashMessageQueue->__call() /srv/www/vhosts/xyz/htdocs/typo3conf/ext/flux/Classes/Service/FluxService.php:458
PHP  14. TYPO3\CMS\Core\Messaging\FlashMessageQueue->enqueue() /srv/www/vhosts/xyz/typo3_src-6.2.14/typo3/sysext/core/Classes/Messaging/FlashMessageQueue.php:259
PHP  15. TYPO3\CMS\Core\Messaging\FlashMessageQueue->addFlashMessageToSession() /srv/www/vhosts/xyz/typo3_src-6.2.14/typo3/sysext/core/Classes/Messaging/FlashMessageQueue.php:53
PHP  16. TYPO3\CMS\Core\Messaging\FlashMessageQueue->getFlashMessagesFromSession() /srv/www/vhosts/xyz/typo3_src-6.2.14/typo3/sysext/core/Classes/Messaging/FlashMessageQueue.php:74
```

typo3 6.2.14
flux 7.2.1
vhs 2.3.3
fluidpages 3.3.1
fluidcontent 4.3.1

after switching back to version 4.2.4 the fatal error is gone.

**Comment by NamelessCoder** [comment] 2015-08-09 14:33
Use the install tool to clear all caches the first time - then you should be able to clear the caches like normal. The error btw comes from the core itself and indicates an object with a dependency injection that has not been detected; in other words: a stale classes cache which now prevents you from clearing the caches.

**Comment by cedricziel** [comment] 2015-08-13 08:48
Sounds like a cache issue as layed out. I'll close this now, but please feel free to reopen if you think it's not.

Cheers,
Cedric

**Comment by munix9** [comment] 2015-08-26 11:14
jepp, don't know where the problem comes from... I don't think that this is a caching problem.

the setup is based on ecodev/typo3-cms-speciality-distribution
after each upgrade-step cache is cleared in backend with install->Important actions->Clear all cache
AND with ```rm -r typo3temp/Cache/*/*``` AND truncating cf_* in db.

nevertheless, the error persists.
after some low flying over the code I've added this and the error is gone
```
--- Classes/Service/ConfigurationService.php
+++ Classes/Service/ConfigurationService.php
@@ -163,7 +163,10 @@
                        $pageTsConfig .= '[PIDinRootline = ' . strval($pageUid) . ']' . LF;
                        $pageTsConfig .= $collectionPageTsConfig . LF;
                        $pageTsConfig .= '[GLOBAL]' . LF;
-                       $this->message('Built content setup for page ' . $pageUid, GeneralUtility::SYSLOG_SEVERITY_INFO, 'Fluidcontent');
+                       $userContext = TYPO3_MODE === 'BE' ? $GLOBALS['BE_USER'] : $GLOBALS['TSFE']->fe_user;
+                       if (FALSE === empty($userContext)) {
+                               $this->message('Built content setup for page ' . $pageUid, GeneralUtility::SYSLOG_SEVERITY_INFO, 'Fluidcontent');
+                       }
                } catch (\RuntimeException $error) {
                        $this->debug($error);
                }
```
I assume that in the scope of the new call in >= 4.3.0 over TableConfigurationPostProcessor
$GLOBALS['BE_USER'] is not properly filled (?!) I've no idea.

**Comment by higidi** [comment] 2015-08-26 12:57
Exactly the same problem here with T3 6.2.14 and flux 7.2.1, but only if fluidcontent 4.3.1 is activated. The issue is the flashmessage that will be generated from fluidcontent, as postet by munix9 above. If you clear the cache via clearCacheMenu it's an ajax requests, so the flash message should be persist in the current user session, but the backend user session is not initialized yet. You can see it in the "init.php" file: Fluidcontent/ConfigurationService is called via Bootstrap::loadExtensionTables() but Bootstrap::initializeBackendUser() gets first called 2 functions later.

**Comment by NamelessCoder** [comment] 2015-08-26 23:47
I suggest we remove the FlashMessage implementation and replace it with a standard syslog via GeneralUtility.

**Comment by higidi** [comment] 2015-08-27 07:54
+1

And we should immediately release the next bugfix version, cause we're currently unable to clear the cache via backend clearCacheMenu.

**Comment by munix9** [comment] 2015-08-27 10:34
ok, sounds good.
in the meantime, not really unexpected, $this->message() in sendDisabledContentWarning() is affected, too.

**Comment by InvisibleKind** [comment] 2015-09-03 09:35
For a sake of completeness: same issue in TYPO3 7.4 and fluidcontent 4.3.1 as well.

**Closed** 2015-09-10 14:20 UTC
