### ISSUE TITLE
Content Element Wizard Tab Name cannot handle spaces

### ISSUE THREAD

**Issue by mkrappitz** [FluidTYPO3/fluidcontent#391] opened 2017-02-21 16:11 UTC
If I setup my new content element wizard tab name as follows all is good, the wizard tab is named "MyElements":

<flux:form id="someid" label="Some Label" description="Some Description" options="{group: 'MyElements'}">
...

Once I use as space in the group name, the wizard tab is named "group_My_Elements" and not "My Elements":

<flux:form id="someid" label="Some Label" description="Some Description" options="{group: 'My Elements'}">
...

TYPO3 7.6.15
flux 8.0.2
fluidcontent 5.0.0

**Comment by mithri** [comment] 2017-03-07 20:12
I can confirm. The same here with flux 8.1 and fluidcontent 5.1

**Comment by steffenk** [comment] 2017-03-12 19:36
first you have to create a translation. If your Tab is named MyElements, you need to add following key to your locallang.xlf:
fluidcontent.newContentWizard.group.MyElements

second my pull request #391 has to be accepted and merge to get the change visible.

**Comment by mkrappitz** [comment] 2017-03-14 15:56
But why not leave it as it is with the name settable directly in the options? 
This ia another kind of breaking change that is not mentioned anywhere.

**Comment by dacostafilipe** [comment] 2017-04-05 13:40
Had the same issue and came to the same conclusion as @steffenk

The main issue here seems to be in buildAllWizardTabGroups and buildWizardTabItem. If more people are interested I could try to make a PR.

For me, @steffenk 's PR #396  would be more then enough if merged.

**Comment by mkrappitz** [comment] 2017-04-05 13:51
Still it would make sense to me to let people just enter whatever they want in the setting withing the viewhelper and just display it as it is. Besides that one could allow to enter a path to a locallang marker and display that. This would be very straightforward to my mind and would not need to break existing installations like now.

**Comment by dacostafilipe** [comment] 2017-04-06 09:15
I've created a PR for this issue here, have a look : #403

**Comment by mkrappitz** [comment] 2017-04-06 09:45
Looks good. Thanks. Did an review with approval.

**Closed** 2017-04-09 10:28 UTC
