### ISSUE TITLE
f:translate no longer working after update to 4.3.1

### ISSUE THREAD

**Issue by mhmli** [FluidTYPO3/fluidcontent#275] opened 2015-09-02 16:09 UTC
When I update this extension from 4.2.4 to 4.3.1 in the Extension Manager, none of the translations (set in Fluid template using e.g. `<f:translate key="LLL:EXT:frp_fce_friendlyworkspace/Resources/Private/Language/locallang.xlf:term.backtotop"/>`) are translated any more. The default English term is pulled from locallang.xlf in all languages. (de.locallang.xlf and so on are available and correctly translated.)

a) is the current CMS version (6.2.14) cross-checked for compatibility when updating via the EM?
b) Has anything changed which isn't documented in CHANGELOG.md?

**Comment by xf-** [comment] 2015-09-02 16:44
<f:*> is core and should work via T3 core. Our function is <v:l key="term.backtotop" /> (also extension and some other parameters possible).
Something wrong with language detection?

**Comment by mhmli** [comment] 2015-09-03 08:27
Language detection is working fine. Content is translated correctly and TS language switching is also working fine. If I update Fluidcontent, Fluid templates break.

**Comment by xf-** [comment] 2015-09-04 20:03
@NamelessCoder i have no cloud what FT3 could break in fluid viewhelper.
Personally i use v:l and only the key (if needed the extension)

**Comment by NamelessCoder** [comment] 2015-09-04 20:45
This absolutely should not be related in any way to the fluidcontent version. Fluid's own translation ViewHelper works completely separately from anything that fluidcontent does. Are you positive you are using the ViewHelper correctly and from a translatable context, e.g. a page that has a proper translation or a backend language that is currently installed and applied in user settings?

@xf- you are sure that no commits slipped in that would force the frontend language? They'd have been rejected, I'm sure, but I don't know for sure. I'm not always around ;)

**Comment by mhmli** [comment] 2015-09-09 13:28
Here's the complete Fluid template, which is one of several which break in this installation. https://gist.github.com/mhmli/9497e3df8c502a55e42c

**Comment by mhmli** [comment] 2015-09-09 14:11
Both the pages and all content elements are correctly and cleanly translated.

The problem occurs in the BE and in the FE, where all other content is correctly shown in the translated language. (Languages are 0: DE, 1: FR, 2: IT. locallang.xlf is English and the files de.locallang.xlf, fr.locallang.xlf and it.locallang.xlf are available, validated, and contain correct translations of all terms.)

Here's the complete Fluid template, which is one of several which break in this installation. https://gist.github.com/mhmli/9497e3df8c502a55e42c 

I've tried removing the `div` around everything and using `{namespace flux=FluidTYPO3\Flux\ViewHelpers}` and `{namespace v=FluidTYPO3\Vhs\ViewHelpers}` instead. That didn't make any difference.

Switching fluidcontent back from 4.3.1 to 4.2.4 (only) and then clearing the backend caches immediately makes the translations work correctly in BE and FE.

**Comment by NamelessCoder** [comment] 2015-09-10 14:35
Hi @mhmli - there is quite literally not a single line of code changed between those versions that has any impact on the global language and/or how fluidcontent perceives this language. There is nothing to explain why your translation calls aren't working (indeed they should) - it just doesn't appear to be anything that we introduced.

I wouldn't mind being proven wrong here if you do find the reason. It could be something silly like the case of a filename or something - whatever it is, please update here and it's something we can help we will ;)

But for now, closing the issue as unable to reproduce and apparently unrelated to fluidcontent.

**Closed by NamelessCoder** 2015-09-10 14:35 UTC
