### ISSUE TITLE
tx_flux_column not set properly

### ISSUE THREAD

**Issue by pixelplant** [FluidTYPO3/fluidcontent#382] opened 2017-02-07 21:35 UTC
Hello

I am using flux 8.0.1 with fluidcontent 5.0.0, on TYPO3 v7.6.15.

I defined a content element that is a container, and it only holds 1 column which I called "left".
This is it's configuration:
```
<f:section name="Configuration">
	<flux:form id="container" options="{group: 'Containers'}">
		<flux:field.input name="title"/>
		<flux:field.input name="subtitle"/>
		<flux:grid>
			<flux:grid.row>
				<flux:grid.column name="left" label="Container content" />
			</flux:grid.row>
		</flux:grid>
	</flux:form>
</f:section>
```

The container works and I can see the "+ content" button inside it, so I can create elements inside it, as children. The problem is that once they are saved, these children should have the value "left" in their "tx_flux_column" field, but the column is empty. This means that once the children is saved, it is no longer displayed in the backend, inside the container, since tx_flux_column is wrong. If I then set this value manually, in the database, the content elements are shown again. It's like the column name I defined on the grid is completely ignored...

**Comment by fiedomedia** [comment] 2017-02-07 22:01
I can confirm this error with TYPO3 8.5.1 with fluidcontent 5.0.0, flux dev-development (94458f9).

If you add a fluidcontent element within fluidcontent then tx_flux_column is empty in the database.
(tx_flux_parent is correct)

But default content elements like header or textmedia worked and tx_flux_column is set.

**Comment by NamelessCoder** [comment] 2017-02-07 22:05
Fixed in fluidcontent's `development` branch, a fix will be released shortly. Thanks for your patience!

**Closed by NamelessCoder** 2017-02-07 22:05 UTC

**Comment by VincentKoehler** [comment] 2017-02-20 11:43
Is there a quickfix for this? I'm currently working on a Typo3 project and this bug makes working with fluidcontent very inconvenient. If you could tell us what lines to change, I would apply them manually.

**Comment by Taskrider** [comment] 2017-02-21 12:48
Isn't fixed in development branch

Can you show me the fixed files or file for this issue

**Comment by mithri** [comment] 2017-02-23 07:15
We have the same problem if we try to insert plugins into a grid column. We are using the dev branch from fluidcontent and flux.

**Comment by pixelplant** [comment] 2017-02-23 11:55
Seems to work fine for me now (latest dev version for fluidcontent, and latest release for flux, running on T3 v7.6.15). Did you clear all the cache? Install tool > Important actions > Clear all cache and "rm -rf *" inside typo3temp?

**Comment by mithri** [comment] 2017-02-23 12:33
Not for me. It works for me with all elements except plugins. Did you try to insert a plugin into a flux grid column?
Thanks!

**Comment by pixelplant** [comment] 2017-02-23 12:36
Yes, I inserted the indexed_search plugin and it shows up just fine. Is it a custom plugin that you developed or one from the system or T3 repo?

**Comment by mithri** [comment] 2017-02-23 12:57
Every kind of plugin isn`t working for us. News or default plugin or own plugin, nothing works. I will test this further on other installations.

**Comment by blueamerican** [comment] 2017-08-01 14:39
I have the same behaviour as described from pixelplant on 7 Feb with this constellation:

TYPO3 8.7.4
fluidcontent 5.2.0
flux 8.2.1

Anybody else with this behaviour?
