### ISSUE TITLE
Page module in language view shows "Fluid Content Area" column

### ISSUE THREAD

**Issue by lsascha** [FluidTYPO3/fluidcontent#209] opened 2015-01-20 16:45 UTC
The Page module if the language view is selected in the top drop-down a "Fluid Content Area" column is displayed below every language column with the content of multi-column elements.

In the column view everything is ok.

//Edit. i am using the TER version fluidcontent 4.1.1,
fluidpages 3.1.2 and Flux 7.1.2

**Comment by danilobuerger** [comment] 2015-01-20 17:33
Duplicate of https://github.com/FluidTYPO3/fluidpages/issues/212

**Closed by danilobuerger** 2015-01-20 17:33 UTC

**Comment by robsonrobi** [comment] 2015-02-03 10:24
I used the js that ist posted in FluidTYPO3/fluidpages#212. Inside the ext_localconf.php of my general plugin i use a hook to add the specific js file "fluidpages.js"

**fluidpages.js**

```javascript
Ext.onReady(function() {
     function contains(selector, text) {
         var elements = document.querySelectorAll(selector);
         return [].filter.call(elements, function(element){
            return RegExp(text).test(element.textContent);
         });
     }
     var childs = contains('div', /^Fluid\ Content\ Area$/);
     childs.forEach(function(element, index, array){
        var remove = element.parentNode.parentNode;
        var removeParent = remove.parentNode;
        removeParent.removeChild(remove);
     });
 });
```

**ext_localconf.php**
```javascript
$GLOBALS['TYPO3_CONF_VARS']['SC_OPTIONS']['typo3/template.php']['preHeaderRenderHook'][] = 'TYPO3\\CMS\\MyTemplate\\Hooks\\BackendDocumentTemplate->fixFluidPages';
```

**BackendDocumentTemplate.php**
```javascript
class BackendDocumentTemplate {

    /**
     * Hook after Rendering
     *
     * @param array $params
     * @param  \TYPO3\CMS\Backend\Template\DocumentTemplate $template
     * @return void
     */
    public function fixFluidPages(array $params, \TYPO3\CMS\Backend\Template\DocumentTemplate &$template)
    {

        $javascriptPath = \TYPO3\CMS\Core\Utility\ExtensionManagementUtility::siteRelPath('mytemplate') . 'Resources/';

        $path = \TYPO3\CMS\Core\Utility\GeneralUtility::getIndpEnv('TYPO3_SITE_URL') . $javascriptPath;
        $file = $path . 'Private/Js/BE/fluidpages.js';

        /** @var \TYPO3\CMS\Core\Page\PageRenderer $pageRenderer */
        $pageRenderer = $template->getPageRenderer();
        $pageRenderer->addHeaderData('<script type="text/javascript" src="' . $file . '"></script>');
    }
} 
```

A simple setting in fluidpages for hiding that column would be smarter, but so it works finally.

**Comment by NamelessCoder** [comment] 2015-02-03 11:41
@robsonrobi would you mind starting that up as a pull request?

**Comment by robsonrobi** [comment] 2015-02-04 10:21
Yes, i can do that. By the way we fenced several problems with localizing. May be someone can help. It is really unusable in that way. :-( https://github.com/FluidTYPO3/flux/issues/755

**Comment by martinhummer** [comment] 2015-02-04 12:26
@robsonrobi thanks for the useful snippet!
