### ISSUE TITLE
No fluidcontent wizard tab

### ISSUE THREAD

**Issue by githubrsys** [FluidTYPO3/fluidcontent#127] opened 2014-02-20 22:53 UTC
As of #126 there´s no Wizard Tab generated.

While 	
<pre>
	&lt;flux:form id=&quot;fluidfluxcontent&quot; label=&quot;Fluid/FluxContent&quot; wizardTab=&quot;test&quot; icon=&quot;Icons/Page.gif&quot;&gt;
</pre>
is ofc set.

**Comment by DrNik** [comment] 2015-02-16 14:05
Hi,
I'm still facing this issue on several instances I manage.
All the instances run on TYPO3 6.2.9 and latest TER versions of fluidtypo3 extensions but at random moments my extension custom backend fluidcontent tabs disappear.
I ran through the IRCLog and checked all the suggestions I found but nothing seems to solve this issue.

Is there any improvement to this? is there something I can do to solve it? Even manually as it seems to happen only on production instances where all the level of caching are up and running.

Of course if you need any more info or support by my side please do not hesitate.

Thanks,
Nicola

**Comment by githubrsys** [comment] 2015-02-16 14:12
> but at random moments my extension custom backend fluidcontent tabs disappear

I assume this happens if the reflection cache is truncated. Then you have to reload the Frame (right click mouse "reload frame") to get the fce tabs instant back, otherwise reload page.

Another reason could be the opcache. Either truncated or not sync.

So I'd investigate here as we do not face your problem as problem.

cheers

**Comment by DrNik** [comment] 2015-02-16 14:27
Hi again,
jut did some more tests clearing caches and it took 2-3 rounds to make tabs appear again.
Though I noticed another odd behaviour that I do not know if it's connected: I ran an extension list update from extension manager and with my surprise it told me that vhs could be updated 2.1.4 to 2.2.0. Thinking of a mistake of mine I updated it as it should be and thought about uninstalling my custom fce extension and re-enabling it to provide a further cache clearing.
With my surprise when I clicked to re-enalbe my extension the extension manager told me that "I could not deactivate VHS cause some other ext were depending on it" and vhs was back to 2.1.4 and upgradable to 2.2.0.

Any clues?

**Comment by NamelessCoder** [comment] 2015-02-16 16:09
Hi DrNik,

Yes - there's an unresolvable dependency problem currently, while we wait to release the next version of `fluidcontent_core`. You can temporarily work around it by manually installing the extension via CLI - because it works regardless of the registered dependency. Do so via CLI:

```
./typo3/cli_dispatch.phpsh extbase extension:install vhs
```

This command will ignore every restraint on the extension and dependencies, including checking if dependencies are installed.

**Comment by DrNik** [comment] 2015-02-16 16:23
Hi Claus,
thanks for the workaround. Installing VHS is not a big deal, though. It gets installed via extension manager indeed. What I don't understand is why it complains about deactivating vhs itself when I try to install another extension and moreover why it seems to downgrade with no reason.

Anyways these could be considered side effects, what gives me the biggest problems are the disappearing tabs, I have several editors locked out from working when it happens.

Thanks,
NIcola

**Comment by NamelessCoder** [comment] 2015-02-16 16:27
I think it's because of the way EM behaves when it tries to resolve dependencies. If another extension "conflicts" (i.e. requires a less-than-installed version of a dependency) EM tries to deactivate that extension and fetch the proper version from TER. That the ends in an error because a third extension depends on VHS, but had it not, VHS would have been downgraded.

The issue is in EM itself but I'm not sure there is an easy solution to it - being quite recursive in nature. Besides, one might argue that composer is a far better choice for handling this. So I'd live with this for now and look forward to the day composer resolves our dependencies and clearly messages errors before actually doing the operation.

Cheers,
Claus

**Comment by DrNik** [comment] 2015-02-16 16:31
I agree with you, it's not even a big deal. As I said the "disappearing tabs" is much more concerning.

Thank you very much for the support,
Nicola

**Comment by BenjaminBeck** [comment] 2015-02-16 20:25
To the ones with the "disappearing tabs" problem:
How did you register your templates/template folders?
I can reproduce the following:
- Content element appears in wizard after Installtool->Clear all caches
- Then, after BE->Clear system caches the element is gone from the wizard

The element that disappeared was registered with TS ("plugin.tx_fluidcontent.collections.bdm_theme_bootstrap")
Elements from a unmodified builder generated extension do not disappear!

**Comment by NamelessCoder** [comment] 2015-02-16 22:23
If you are using the `development` branches, the information from https://fluidtypo3.org/blog/news/coming-changes-in-flux-72.html applies to you already and you should make yourself familiar with it ;)

**Comment by DrNik** [comment] 2015-02-16 23:20
Hi Benjamin,
hoping I did not misunderstand your suggestion i re-check my disappearing-tabs ext,but I found nowhere something like what you pointed out.
My TS templates are registered like this:
`plugin.tx_contentpack.view {
templateRootPath = EXT:contentpack/Resources/Private/Templates/
partialRootPath = EXT:contentpack/Resources/Private/Partials/
layoutRootPath = EXT:contentpack/Resources/Private/Layouts/
}`

Am I correct or did I miss something?

Thanks once more,
Nicola

**Comment by BenjaminBeck** [comment] 2015-02-17 11:14
@DrNik what i meant with registering is the way how you tell fluidcontent that there are templates to process. Maybe the cause for the disappearing elements is the usage of a deprecated method of registering the templates paths - like the "collection" thing..
You could try to generate a fluidcontent provider extension with the [builder](https://github.com/FluidTYPO3/builder) extension and test if those elements/tabs do also disappear.
Then you can compare the two and find the cause ..

**Comment by DrNik** [comment] 2015-02-17 11:17
My extension is already generated via builder extension, sorry I forgot to mention in before, but for sure I'll give it another round.
The piece of TS I posted is the one you where referring to (apart from deprecated methods)?!

Nicola

**Comment by NamelessCoder** [comment] 2015-02-17 16:05
Hi DrNik,

Can you gist/pastebin the contents of the `content` column of the only cache record presently in the `cf_fluidcontent` table in the DB of your site? There may be an explanation in the `[PIDinRootline = xyz]` conditions that were generated.

There are three other explanations I can think of:

* Cache lifetime is set to a very low number or you have replaced the fluidcontent cache with a NULL cache and are reloading the content wizard. The wizard gets rebuilt as soon as any `fluidcontent` context is initiated - but this doesn't happen on the very first load of the wizard when no cache record exists. The wizard itself doesn't use `fluidcontent` to read the elements - it uses the cached piece of pageTSconfig only.
* Custom pageTSconfig exists in some locations of your page tree or is applied from your "UC" variable (user configuration, a property of the `be_sessions` table). If syntax errors are present in pageTSconfig that is applied in front of the `fluidcontent` pageTSconfig or the configuration is modified, TYPO3 may not be able to properly read the configuration.
* The WizardItemsHookSubscriber of `fluidcontent` is processing the array incorrectly for some unknown reason - however, if either of the other two problems are the cause, the WizardItemsHookSubscriber would receive incorrect input and would obviously behave incorrectly, so check this last.

Your other setup seems to be perfectly okay. Provider Extensions generated by `builder` will (given correct input) always generate valid and up-to-date implementations so the cause has to be in other site configuration or processing hereof, or it is a bug that's gone unnoticed in `fluidcontent` for a long, long time.

**Comment by NamelessCoder** [comment] 2015-02-17 16:08
Reopened until confirmed/explained.

**Comment by DrNik** [comment] 2015-02-17 16:38
Hi @NamelessCoder ,
thanks for the hints...
I tried to collect as many data as possible about what your were pointing out:
* I faced the same issue on 2 different istances completely isolated from each other, but in none of them cache is set to NULL and lifetime is untouched.
* I don't think TSConfig is the problem cause in one istance I have no custom tsconfig at all.
* I leave the third point to you as I understand it's a sort of "last chance"

What I discovered that surprised me is that:
1. instance One: tabs disappeared -> Only 1 record in cf_fluidcontent
2. Istance Two: tabs visible -> 2 records in cf_fluidcontent

Want me to send all 3 records content?

Thanks,
Nicola

**Comment by DrNik** [comment] 2015-02-17 16:51
UPDATE: I checked the three cf_fluidcontent records and the problem is pretty clear, even though I have no clue how it gets generated or could be solved.
Despite the number of records where the tabs are visible (Istance Two) the conditions like:
`[PIDinRootline = 1]
[GLOBAL]`
are filled up with, what looks to me like, TSConfig settings of  my fces.
On the other hand, on the instance with gone tabs (Istance One) those conditions are all empty, as I pasted above.

Does this help to figure it out?

Nicola

**Comment by NamelessCoder** [comment] 2015-02-17 17:04
It may point to a problem in resolving the TypoScript. The following must be true for a valid set of templates to be generated in a `PIDinRootline` clause:

* Page containing root TypoScript template must be set to `siteroot` under Behavior.
* TypoScript template must either be set to root or include/base-on a root template.
* TypoScript template must either not define template paths or must define a valid set of template paths for your extension.

This will allow `fluidcontent` to *detect* the template locations which causes a condition block to be added. The TypoScript then applies to the page tree as it normally would (so beware, if you have content records stored in a sysfolder in which the TypoScript is *not* available, you won't be able to create elements there). I suspect that maybe your instance that has the problem, either did not mark the `sys_template` or the `pages` record as "root" under Behavior.

All of this takes place in the ConfigurationService from fluidcontent, in the various `build*` methods. The templates will be parsed and rendered during this process so if any template depends on some TypoScript settings, those must also be defined (at least defaults) on each root TS template.

**Comment by DrNik** [comment] 2015-02-17 17:11
@NamelessCoder sorry to "disappoint" you but both the 2 istances that faced the problem fullfill your requirements (I'll have them checked again though).
One of the 2 has even a very simple and standard configuration about the points you were concerned about.

Don't know what else to think about.

Thanks again,
NIcola

**Comment by ste101** [comment] 2015-03-09 09:11
@NamelessCoder
Same problem here. Sometimes the tab disappears. After clearing all cache in the install tool the tab appears again.
I could give you access to an installation if you want.

Regards
Stephan

**Comment by NamelessCoder** [comment] 2015-03-15 13:04
Hi guys,

The one cause for tabs disappearing that I've been able to determine, is if you time the loading of the "new content wizard" so you hit it **exactly** after the cached pageTSconfig record has expired. The tabs then go away.

But loading **any** backend page or module or clearing the caches brings back the tabs immediately. I'm pretty sure that's the case @ste101 was/is encountering. On a side note, anything that (re-)configures the caches (in particular VariableFrontEnd and TYPO3DatabaseBackend) or somehow hooks into them might affect this.

The one thing I can do to remove *that* as a cause, is to give the fluidcontent cache much longer life (say, a handful of years). I'll be doing that in a short while.

@DrNik if that change does nothing to prevent your problems I'm afraid I am out of potential explanations. The one thing about your setup I can spot that is different, would be the empty cache record generated in fluidcontent's cache. If you were able to determine why that happens it would bring us closer to an explanation or maybe even give you a solution. If/when you do discover such a cause I would be **very** happy about a pull request or just a new issue. Maybe you can join forces with @mhmli to compare your setups?

@mhmli Sorry I missed your comments earlier - hopefully the thread since then has helped you solve both your problems but if not: I'd like you to create a new issue about the labels going missing in localised contexts, if that is still a problem (on 6.2.10 or 7.1).

Apologies if this disappoints anyone, but I have to close this as unreproducible behavior. If any one of you come closer to an explanation then please don't hesitate to comment here - or open up a new issue.

**Comment by mhmli** [comment] 2015-03-16 08:48
Thanks for the extensive answer Claus. We'll have to re-analyse the problem
after a future update to the newest core and extension versions, as it's
pointless to try and debug an outdated installation and extension version.

**Comment by ste101** [comment] 2015-03-16 10:26
@NamelessCoder
Thank you for your explanation but unfortunatelly loading another backend page does not bring the tab back. Also deleting the folder typo3temp/Cache/ does not bring the tab back.
Only the install tool button 'clear all cache' brings the tab back.

**Comment by fgerards** [comment] 2015-04-09 09:29
I can confirm the tab-disappearing under TYPO3 6.2.11 and Flux 6.x.

**Comment by alexxB** [comment] 2015-04-21 09:26
we are also fighting with the problem of disappearing tabs on several installations.

**Comment by mkrappitz** [comment] 2015-04-23 15:59
Same here on 6.2.12, flux 7.2.0, fluidcontent 	4.2.1. Same error behaviour as explained by all other people before me.

**Comment by ste101** [comment] 2015-05-18 09:50
My colleague found a solution. Add this if in Clases/Service/ConfigurationService.php at line 152:
```if (TYPO3_MODE != 'BE') {```

**Comment by mkrappitz** [comment] 2015-05-18 12:50
Could you provice the sourrounding lines as well please or a patch file? 
In the current version there are different line numbers.

**Comment by fgerards** [comment] 2015-05-21 12:16
it is in the function writeCachedConfigurationIfMissing().
In 4.2.1 it is  around line 112, but the if-case is different and the logic is, so the surrounding condition might be if (TYPO3_MODE == 'BE') ...

**Comment by mhmli** [comment] 2015-05-22 11:33
First tests with a live environment have produced positive results for a handful of users. More extensive testing to follow.

**Comment by mkrappitz** [comment] 2015-05-22 11:34
Same here! Thanks for providing this!

**Comment by fgerards** [comment] 2015-05-24 14:45
Plz provide a patch file working with the latest fluidcontent version or do a pull-request after u forked and fixed the issue

**Comment by bjo3rnf** [comment] 2015-05-25 07:16
> Plz provide a patch file working with the latest fluidcontent version or do a pull-request after u forked and fixed the issue
:+1:

**Comment by ste101** [comment] 2015-05-25 21:14
Is it realy a fix or only a workaround?
@NamelessCoder: Could you tell us what you think?

**Comment by coding46** [comment] 2015-06-05 13:49
Fixed by ed1cffa5a6cf96a28bb90268b36c1477f64f286b

**Closed by coding46** 2015-06-05 13:49 UTC

**Comment by LapSiLap** [comment] 2015-08-14 12:36
If you still wonder why the tabs disappear, here's an explanation and why it happens without the fix:
The pageTS cache in cf_fluidcache expires ( you can edit the expires field manually to cause it too )
Someone visits the a non-cached page in FE and generates incorrect pageTS*, which gets cached in cf_fluidcache.

*For our fluidcontent it was because we register FCEs (Tx_Flux_Core::registerProviderExtensionKey) in ext_tables.php only, and by adding the same line in ext_localconf.php, FE could generate correct pageTS.
