### ISSUE TITLE
tx_fed_fcefile empty value leads to webserver 500 Error

### ISSUE THREAD

**Issue by githubrsys** [FluidTYPO3/fluidcontent#240] opened 2015-06-04 07:09 UTC
flux on
76a28ef1a67cd5e16e7b1d0d33c7a915ee5c5bfb

fluidcontent on
bc7d2226d784c4545b38b6c7b927a1be650c7019

6.2 core on 
02d54691fc808c4c4a70b61967f7ee11ec9ccaeb

If for any reason a fce element does not get a tx_fed_fcefile value, the page module overview breaks on that certain page. You have 2 choices: enter a value into the field manually or remove the entry from the database. Even setting on hidden by list module or delete it with list module does not change anything. The page module still breaks. IMHO this should not happen and a kind of fallback done that does not lead to a non editable page.

``` Fatal error: Uncaught exception 'TYPO3\CMS\Fluid\View\Exception\InvalidTemplateResourceException' with message 'Template could not be loaded. I tried "/var/www/web12/html/t3_live/typo3conf/ext/fluidcontent/Resources/Private/Templates/Content/Index.html"' in /var/www/web12/html/t3_live/TYPO3.CMS1/typo3/sysext/fluid/Classes/View/TemplateView.php:369 Stack trace: #0 /var/www/web12/html/t3_live/typo3conf/ext/flux/Classes/View/ExposedTemplateView.php(152): TYPO3\CMS\Fluid\View\TemplateView->getTemplatePathAndFilename(NULL) #1 /var/www/web12/html/t3_live/TYPO3.CMS1/typo3/sysext/fluid/Classes/View/TemplateView.php(316): FluidTYPO3\Flux\View\ExposedTemplateView->getTemplatePathAndFilename(NULL) #2 /var/www/web12/html/t3_live/typo3conf/ext/flux/Classes/View/ExposedTemplateView.php(132): TYPO3\CMS\Fluid\View\TemplateView->getTemplateIdentifier() #3 /var/www/web12/html/t3_live/typo3conf/ext/flux/Classes/View/ExposedTemplateView.php(167): FluidTYPO3\Flux\View\ExposedTemplateView->getParsedTemplate() #4 /var/www/web12/html/t3_live/typ in /var/www/web12/html/t3_live/TYPO3.CMS1/typo3/sysext/fluid/Classes/View/TemplateView.php on line 369 ```

cheers

**Comment by NamelessCoder** [comment] 2015-06-04 13:56
Duplicate of https://github.com/FluidTYPO3/flux/issues/830

**Closed by NamelessCoder** 2015-06-04 13:56 UTC
