### ISSUE TITLE
Sporadic error when inserting a fluid content element

### ISSUE THREAD

**Issue by q-bic** [FluidTYPO3/fluidcontent#201] opened 2014-12-02 09:52 UTC
When inserting a fluidcontent content element at different positions in the content area, sometimes an error occurs.

For example:
When inserting a content element at the first position everything works fine. When inserting it for example at the second position, it's not working as intended. I have to mention that it's not always the second position. for me this seems pretty much random, but the first position always works i guess.
![second-pos](https://cloud.githubusercontent.com/assets/7699805/5260472/819e1bf0-7a0f-11e4-9b5b-3db6fa34bb99.png)
After selecting a content element (doesn't matter which one) the following happens:
![error](https://cloud.githubusercontent.com/assets/7699805/5260493/cae1aa20-7a0f-11e4-859a-4a030d637e12.png)
It is not possible to select a fluid content element from the select field, because the only option available is "Fluid Content Type".

This happens with:
TYPO3 CMS 6.2.6 and 6.2.8
Flux - latest git version
Fluidpages - latest git version
Fluicontent - latest git version
VHS - latest git version

***UPDATE***
When inserting an element on the first position an then dragging it to the desired position, everything works fine also.
If an element is inserted at a position where the problem occurs, it is possible to save the element and reopen it. Then the desired fluid content element can be selected.

**Comment by xf-** [comment] 2015-01-17 15:40
Missing translation - cleared cache in Install tool?
Maybe copy the source code of the selectbox from a inspecttool.
Do you use different ids for different FCEs?

**Comment by NamelessCoder** [comment] 2015-03-15 12:44
Since this selector uses the same code that generates the cached entries for the wizard tab, I suspect it is related to this issue:

https://github.com/FluidTYPO3/fluidcontent/issues/127

The only possible reason I can think of is that you are hitting a case where the system cache has *just* been cleared and you have not yet loaded/reloaded the page module or backend to force the content definitions to regenerate.

I will take the liberty of closing this one, at least until a consistently reproducible cause can be determined. Just FYI, personally I am only aware of this issue, the one linked above and one additional case where the content wizard would not load at all - which was caused by a cache not having been initialised because `fluidcontent` was installed manually through PackageStates and the install tool was not run.

**Closed by NamelessCoder** 2015-03-15 12:44 UTC
