### ISSUE TITLE
question regarding be permissions

### ISSUE THREAD

**Issue by svenlahann** [FluidTYPO3/fluidcontent#282] opened 2015-10-04 20:12 UTC
hi, 
is it possible at the moment to restrict access to specific custom content elements to certain backend usergroups / users?

**Comment by cweiske** [comment] 2015-10-26 09:19
I'd also like to see this feature.

**Comment by cweiske** [comment] 2015-10-26 10:03
Probably a duplicate of FluidTYPO3/flux/issues/197.

**Comment by NamelessCoder** [comment] 2015-12-18 11:45
Implemented :)

**Closed by NamelessCoder** 2015-12-18 11:45 UTC
