### ISSUE TITLE
translation error of fce inside fce in v 7.6 

### ISSUE THREAD

**Issue by blueamerican** [FluidTYPO3/fluidcontent#347] opened 2016-04-15 12:14 UTC
hi,

if i click the translate button in a nested fce, the translation process (i choose translate, not copy) hangs in the last step and isn't finished.

if the fce is not nested, it works.

best regards,
blueamerican

**Comment by NamelessCoder** [comment] 2016-06-24 12:03
Closed as duplicate of #1120, please subscribe to that issue for further updates!

**Closed by NamelessCoder** 2016-06-24 12:03 UTC
