### ISSUE TITLE
Server error after version upgrade

### ISSUE THREAD

**Issue by der-peer** [FluidTYPO3/fluidcontent#328] opened 2015-12-26 09:40 UTC
Hi@all,

I have multiple Typo3-instances, which I'm going to get up to the current LTS.

But on two of them I have severe errors, and I'm not sure if there are server errors or if it's some fluidcontent issue. Any help would be appreciated. Frontend simply throws Error 500, server log states "Premature end of script headers"... not very helpful.

Working versions:
Typo3 7.4.0, PHP 5.5.30 (one with IonCube, one without), fluidcontent 4.3.3

Not working:
Typo3 7.6.2, PHP 5.5.30 (with IonCube), fluidcontent 4.4.0, Builder 1.1.0
Builder throws:

/var/www/typo3dev/typo3conf/ext/fluidcontent//Classes/Backend/ContentTypeFilter.php

exception 'Exception' with message 'Failed loading /opt/ioncube/current/ioncube_loader_lin_5.5.so: /opt/ioncube/current/ioncube_loader_lin_5.5.so: undefined symbol: zend_execute_ex' in /var/www/typo3dev/typo3conf/ext/builder/Classes/Service/SyntaxService.php:125 Stack trace: #0 /var/www/typo3dev/typo3conf/ext/builder/Classes/Service/SyntaxService.php(150): FluidTYPO3\Builder\Service\SyntaxService->syntaxCheckPhpFile('/var/www/typo3dev...')  #1 /var/www/typo3dev/typo3conf/ext/builder/Classes/Controller/BackendController.php(173): FluidTYPO3\Builder\Service\SyntaxService->syntaxCheckPhpFilesInPath('/var/www/typo3dev...')  #2 [internal function]: FluidTYPO3\Builder\Controller\BackendController->syntaxAction(Array, Array, Array, Array)  #3 /var/www/typo3dev/typo3_src-7.6.2/typo3/sysext/extbase/Classes/Mvc/Controller/ActionController.php(283): call_user_func_array(Array, Array)  #4 /var/www/typo3dev/typo3_src-7.6.2/typo3/sysext/extbase/Classes/Mvc/Controller/ActionController.php(176): TYPO3\CMS\Extbase\Mvc\Controller\ActionController->callActionMethod()  #5 /var/www/typo3dev/typo3_src-7.6.2/typo3/sysext/extbase/Classes/Mvc/Dispatcher.php(86): TYPO3\CMS\Extbase\Mvc\Controller\ActionController->processRequest(Object(TYPO3\CMS\Extbase\Mvc\Web\Request), Object(TYPO3\CMS\Extbase\Mvc\Web\Response)) #6 /var/www/typo3dev/typo3_src-7.6.2/typo3/sysext/extbase/Classes/Mvc/Web/BackendRequestHandler.php(32): TYPO3\CMS\Extbase\Mvc\Dispatcher->dispatch(Object(TYPO3\CMS\Extbase\Mvc\Web\Request), Object(TYPO3\CMS\Extbase\Mvc\Web\Response)) #7 /var/www/typo3dev/typo3_src-7.6.2/typo3/sysext/extbase/Classes/Core/Bootstrap.php(206): TYPO3\CMS\Extbase\Mvc\Web\BackendRequestHandler->handleRequest() #8 /var/www/typo3dev/typo3_src-7.6.2/typo3/sysext/extbase/Classes/Core/Bootstrap.php(193): TYPO3\CMS\Extbase\Core\Bootstrap->handleRequest() #9 /var/www/typo3dev/typo3_src-7.6.2/typo3/sysext/backend/Classes/Http/BackendModuleRequestHandler.php(209): TYPO3\CMS\Extbase\Core\Bootstrap->run('', Array) #10 /var/www/typo3dev/typo3_src-7.6.2/typo3/sysext/backend/Classes/Http/BackendModuleRequestHandler.php(92): TYPO3\CMS\Backend\Http\BackendModuleRequestHandler->dispatchModule('tools_BuilderTx...') #11 /var/www/typo3dev/typo3_src-7.6.2/typo3/sysext/core/Classes/Core/Bootstrap.php(302): TYPO3\CMS\Backend\Http\BackendModuleRequestHandler->handleRequest(Object(TYPO3\CMS\Core\Http\ServerRequest)) #12 /var/www/typo3dev/typo3_src-7.6.2/typo3/sysext/backend/Classes/Http/Application.php(94): TYPO3\CMS\Core\Core\Bootstrap->handleRequest(Object(TYPO3\CMS\Core\Http\ServerRequest)) #13 /var/www/typo3dev/typo3_src-7.6.2/typo3/index.php(20): TYPO3\CMS\Backend\Http\Application->run() #14 [internal function]: {closure}() #15 /var/www/typo3dev/typo3_src-7.6.2/typo3/index.php(21): call_user_func(Object(Closure)) #16 {main}

Same error on ext/fluidcontent//Classes/Service/ConfigurationService.php

Also not working:
Typo3 7.6.2, PHP 5.5.30 (no IonCube), fluidcontent 4.4.0, Builder 1.1.0
Builder output:

/var/www/t3test/typo3conf/ext/fluidcontent//Classes/Backend/ContentTypeFilter.php

exception 'Exception' with message 'PHP Parse error: syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in /var/www/t3test/typo3conf/ext/fluidcontent//Classes/Backend/ContentTypeFilter.php on line 111' in /var/www/t3test/typo3conf/ext/builder/Classes/Service/SyntaxService.php:125 Stack trace: #0 /var/www/t3test/typo3conf/ext/builder/Classes/Service/SyntaxService.php(150): FluidTYPO3\Builder\Service\SyntaxService->syntaxCheckPhpFile('/var/www/t3test...') #1 /var/www/t3test/typo3conf/ext/builder/Classes/Controller/BackendController.php(173): FluidTYPO3\Builder\Service\SyntaxService->syntaxCheckPhpFilesInPath('/var/www/t3test...') #2 [internal function]: FluidTYPO3\Builder\Controller\BackendController->syntaxAction(Array, Array, Array, Array) #3 /var/www/t3test/typo3_src-7.6.2/typo3/sysext/extbase/Classes/Mvc/Controller/ActionController.php(283): call_user_func_array(Array, Array) #4 /var/www/t3test/typo3_src-7.6.2/typo3/sysext/extbase/Classes/Mvc/Controller/ActionController.php(176): TYPO3\CMS\Extbase\Mvc\Controller\ActionController->callActionMethod() #5 /var/www/t3test/typo3_src-7.6.2/typo3/sysext/extbase/Classes/Mvc/Dispatcher.php(86): TYPO3\CMS\Extbase\Mvc\Controller\ActionController->processRequest(Object(TYPO3\CMS\Extbase\Mvc\Web\Request), Object(TYPO3\CMS\Extbase\Mvc\Web\Response)) #6 /var/www/t3test/typo3_src-7.6.2/typo3/sysext/extbase/Classes/Mvc/Web/BackendRequestHandler.php(32): TYPO3\CMS\Extbase\Mvc\Dispatcher->dispatch(Object(TYPO3\CMS\Extbase\Mvc\Web\Request), Object(TYPO3\CMS\Extbase\Mvc\Web\Response)) #7 /var/www/t3test/typo3_src-7.6.2/typo3/sysext/extbase/Classes/Core/Bootstrap.php(206): TYPO3\CMS\Extbase\Mvc\Web\BackendRequestHandler->handleRequest() #8 /var/www/t3test/typo3_src-7.6.2/typo3/sysext/extbase/Classes/Core/Bootstrap.php(193): TYPO3\CMS\Extbase\Core\Bootstrap->handleRequest() #9 /var/www/t3test/typo3_src-7.6.2/typo3/sysext/backend/Classes/Http/BackendModuleRequestHandler.php(209): TYPO3\CMS\Extbase\Core\Bootstrap->run('', Array) #10 /var/www/t3test/typo3_src-7.6.2/typo3/sysext/backend/Classes/Http/BackendModuleRequestHandler.php(92): TYPO3\CMS\Backend\Http\BackendModuleRequestHandler->dispatchModule('tools_BuilderTx...') #11 /var/www/t3test/typo3_src-7.6.2/typo3/sysext/core/Classes/Core/Bootstrap.php(302): TYPO3\CMS\Backend\Http\BackendModuleRequestHandler->handleRequest(Object(TYPO3\CMS\Core\Http\ServerRequest)) #12 /var/www/t3test/typo3_src-7.6.2/typo3/sysext/backend/Classes/Http/Application.php(94): TYPO3\CMS\Core\Core\Bootstrap->handleRequest(Object(TYPO3\CMS\Core\Http\ServerRequest)) #13 /var/www/t3test/typo3_src-7.6.2/typo3/index.php(20): TYPO3\CMS\Backend\Http\Application->run() #14 [internal function]: {closure}() #15 /var/www/t3test/typo3_src-7.6.2/typo3/index.php(21): call_user_func(Object(Closure)) #16 {main}

Same error on ext/fluidcontent//Classes/Service/ConfigurationService.php

**Comment by NamelessCoder** [comment] 2015-12-26 14:55
Hi @der-peer,

I'd like you to check is which actual file is causing this, e.g. ContentController.php, and then look into that file to check if it's valid PHP. The error is raised during syntax checking and could indicate that those files were incorrectly generated (class names get written based on vendor/extension-name that you provide and any illegal characters there would result in .php files with syntax errors in the place you quote).

**Comment by der-peer** [comment] 2015-12-26 16:28
Hi @NamelessCoder,
the Builder syntax check throws the error for
- ext/fluidcontent/Classes/Backend/ContentTypeFilter.php
- ext/fluidcontent/Classes/Service/ConfigurationService.php.
But to me these files seem ok.

I really can't see how to go on digging into this... I only have some basic coding skills. I'm more user than programmer...

**Comment by NamelessCoder** [comment] 2016-02-03 10:26
@der-peer Sorry, but I've got to close this one as caused by the environment and/or setup. Some of it points to the ioncube loader PHP module and the other error looks like something usually caused by the PHP version being too low (or the PHP parser being patched with modules that change how classes are parsed/cached/optimised). You've got to look for the cause in the setup, for example by comparing the working setups with the non-working ones, in terms of which PHP modules are loaded and what their configurations are.

It might even be a task for the hosting support team if you're on a managed server.

**Closed by NamelessCoder** 2016-02-03 10:26 UTC
