### ISSUE TITLE
Fluid Content type not selected - edit this element in the TYPO3 backend to fix this! 

### ISSUE THREAD

**Issue by lukastaferner** [FluidTYPO3/fluidcontent#358] opened 2016-06-22 10:02 UTC
Hi, thanks for your great extension :)

We experience problems with fluidcontent Elements showing this error messgae in the FE:

Fluid Content type not selected - edit this element in the TYPO3 backend to fix this! 

Content uid: []

Tis is how the backend looks like:
![image](https://cloud.githubusercontent.com/assets/16412576/16262588/841fe77a-3870-11e6-8f37-2dbc9ccf0e1a.png)

Saving the element in the backend will fix the issue for some time (cache-related?) but ?no_cache=1 will not remove the error. Unfortunately I do not yet know how to reproduce it, I will post updates.

fluidcontent 4.4.1
flux 7.4.0
vhs 2.4.0

Thank you,

Lukas

**Comment by NamelessCoder** [comment] 2016-06-23 11:58
Hi Lukas,

Thanks for the kind words :)

We are affected by https://forge.typo3.org/issues/76509 which causes the `fluidcontent_content` field to reset values in the GUI and/or not respect the values that *do* get sent to the DataHandler.

Please follow the issue there (as a solution in TYPO3 is required; best we could hope for is some workaround and if one can be found I'll note it in that issue). If you can provide potential solutions (for FormEngine) that would be even better. We expect though that once fixed, the fix will be included in all maintained versions of TYPO3 from the next bug fix release (so we may not even need a workaround - we will of course evaluate as it moves along).

On a side note I am prevented from implementing a proper TCA-based template file selector for fluidpages for now, for the exact same reason. A solution or even workaround would be pretty good to have at this point.

I'll close this issue since technically it isn't a problem with fluidcontent - technically it is a regression that needs fixing in the core itself. Hate to say it, but this is one thing we can't solve on our side :/

**Closed by NamelessCoder** 2016-06-23 11:58 UTC

**Comment by lukastaferner** [comment] 2016-06-30 10:45
Hi NamelessCoder,

thank you for the explanation, I found another reason for this (very special) case:
I included a custom Vewhelper that returns a rendered Fluidtemplate itself . . . . I used DI to inject TYPO3\CMS\Fluid\View\StandaloneView which caused the first hit on the page (after clearing Cache) to produce the error. Any subsequent request to the page will render without problems. I worked around the issue by using objectManager: 
$myView = $this->objectManager->get('TYPO3\CMS\Fluid\View\StandaloneView');

I am not sure if this is Core-related, but I guess so (I guess the Fluid instances get mixed up).

Maybe this will help anyopne facing the same problem!

Greetings,

Lukas
